# -*- coding: utf-8 -*-
"""ling575_hw2_collab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BsQJE-LEILrHd2-YtpZ-U_fsC7cLv902
"""

import sys
import re

#order class
class pizzaOrder:
    def __init__(self):
        self.list_of_pizzas = []
        self.cost_of_pizzas = []
        self.total_cost = 0
        self.order_name = ''
        self.delivery = False
        self.address = ''
        self.phone = ''


      #setter functions
      def set_list_of_pizzas(self, pizza_obj):
        self.list_of_pizzas.append(pizza_obj)

      def set_cost_of_pizzas(self, cost):
        self.cost_of_pizzas.

      def set_total_cost(self):
        self.total_cost = sum(self.cost_of_pizzas)

      def set_order_name(self, x):
        self.order_name = x

      def set_delivery(self, x):
        self.delivery(x)

      def set_address(self, x):
        self.address = x

      def set_phone(self, x):
        self.phone = x

#pizza class
class pizza:
    def __init__(self):
        self.type_of_pizza = ''
        self.size_of_pizza = ''
        self.crust_of_pizza = ''
        self.cost_of_pizza = 0

        self.prices = {"type":{"Hawaiian": 6, "Vegan": 8},
                       "size":{"small":{"thin":10, "regular":10, "deep":12, "gf":15}, 
                               "medium":{"thin":12, "regular":12, "deep":14, "gf":18}, 
                               "large":{"thin":14, "regular":14, "deep":18, "gf":21}}
        
    def set_type_of_pizza(self,x):
        self.type_of_pizza = x
        self.cost_of_pizza += self.prices[x]

    def set_size_of_pizza(self,x):
        self.size_of_pizza = x
        
    def set_crust_of_pizza(self,x):
        self.crust_of_pizza = x
        self.cost_of_pizza += self.prices[self.size_of_pizza][x]

state_machine = {"start": {"hawaiian":"add_pizza"},
                 "add_pizza": {"large":"change_size"},
                 "change_size": {"delivery":"delivery_type"},
                 "delivery_type": {"alex":"add_name"},
                 "add_name": {"123-123-1234":"add_phone"},
                 "add_phone": {"yes":"confirm_order"}
                }

output_reel = {"start":"Welcome to the pizza ordering system. What would you like?",
                 "add_pizza":"What size?" ,
                 "change_size":"Pick-up or delivery?" ,
                 "delivery_type": "Name?",
                 "add_name":"Phone number?" ,
                 "add_phone":"Got your order for a large Hawaiian on regular crust. Is that okay?",
                 "confirm_order":"Your order has been received. It will be delivered in 30 minutes or less and cost $20.00."
                }

order_x = pizzaOrder()
pizza_x = pizza()

currState = 'start'
while currState != 'confirm_order':
    print(output_reel[currState])
    in_value = input()
    currState = state_machine[currState][in_value]
    if currState == 'add_pizza':
        pizza_x.set_type_of_pizza(in_value)
    elif currState == 'change_size':
        pizza_x.set_size_of_pizza(in_value)
    elif currState == 'add_name':
        order_x.set_order_name(in_value)
        
    if currState == 'confirm_order':
        print(output_reel[currState])